<!--
 vim: filetype=html
-->
	<div id="container">

		<a href="https://github.com/rixed/RobiNet">
			<img style="position: fixed; top: 0; right: 0; border: 0;" src="http://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png" alt="Fork me on GitHub" />
		</a>


		<h1>RobiNet</h1>
		<div id="menu">
			<a href="index.html" id="home_link">Home</a>
			<a href="download.html" id="download_link">Download</a>
			<a href="packets.html" id="packets_link">Packets</a>
			<a href="hosts.html" id="hosts_link">Fake Hosts</a>
			<a href="nets.html" id="nets_link">Fake Networks</a>
			<a href="scenarii.html" id="scenarii_link">Scenarii</a>
			<a href="metrics.html" id="metrics_link">Metrics</a>
		</div>

